### ISSUE TITLE
WARN ! dav config is causing ever-increasing httpd config file on el7 (and httpd reloads, and syslogs flooding) !

### ISSUE THREAD

**Issue by fschaer** [cern-it-sdc-id/puppet-dmlite#19]
Hi,

This : 

https://github.com/cern-it-sdc-id/puppet-dmlite/blob/18c9c1903fbf54f029180800b4ad6e11d56bb3bc/manifests/dav/config.pp#L175-L179

Is causing the required line to be duplicated each time puppet runs !
e.g : 

```
# grep "LoadModule mpm_event_module modules/mod_mpm_event.so" /etc/httpd/conf.modules.d/00-mpm.conf |wc -l
2118
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

The file_line "match" parameter is un-needed, and this is what's causing duplication (it's not a problem to leave the commented line in place, but if replaced, then the match will not match anymore and the file line will be duplicated)

The syslog flooding messages look like this : 
```
Jan  8 03:37:01 -hostname- httpd[173967]: [Mon Jan 08 03:37:01.443800 2018] [so:warn] [pid 173967:tid 140221016840320] AH01574: module mpm_event_module is already loaded, skipping
Jan  8 03:37:01 -hostname- httpd[173967]: [Mon Jan 08 03:37:01.443810 2018] [so:warn] [pid 173967:tid 140221016840320] AH01574: module mpm_event_module is already loaded, skipping
Jan  8 03:37:01 -hostname- httpd[173967]: [Mon Jan 08 03:37:01.443817 2018] [so:warn] [pid 173967:tid 140221016840320] AH01574: module mpm_event_module is already loaded, skipping
Jan  8 03:37:01 -hostname- httpd[173967]: [Mon Jan 08 03:37:01.443825 2018] [so:warn] [pid 173967:tid 140221016840320] AH01574: module mpm_event_module is already loaded, skipping
Jan  8 03:37:01 -hostname- httpd[173967]: [Mon Jan 08 03:37:01.443837 2018] [so:warn] [pid 173967:tid 140221016840320] AH01574: module mpm_event_module is already loaded, skipping
```

I commented out the match param here and puppet stopped duplicating the conf and reloading apache

**Comment by andrea-manzi** [comment]
Hi Fred,
this problem  has been already reported  ( it happens with stdlib >= 4.15 and being CERN still stuck 4.15  we didn't see it).

and it's fixed since a while on the develop branch 

https://github.com/cern-it-sdc-id/puppet-dmlite/issues/18

the plan was to release it together with a new Major release with quite some changes due to dmlite 1.11.0, but given that everything is delayed i'm going to release this fix only tomorrow to puppetforge ( and i'll do the same for the xrootd module)
thanks and sorry for the issue
Andrea

**Comment by andrea-manzi** [comment]
fix pushed to puppetforge ( v.0.5.4)
https://forge.puppet.com/lcgdm/dmlite
thanks
Andrea
